siteTitle: PERMITAS
siteDescription: NIL
logo: /images/brand/logo.png
socialInstagram: instagram.com
socialLinkedIn: linkedin.com
contactEmail: officialemail@gmail.com
contactPhone: +91 9884640133
footerText: Investments are subjected to market risks
navigation: []
