siteTitle: PERMITAS
siteDescription: NIL
socialInstagram: instagram.com
socialLinkedIn: linkedin.com
contactEmail: officialemail@gmail.com
contactPhone: +91 9884640133
footerText: Happy birthday akka!!
navigation: []
