siteTitle: PERMITAS
siteDescription: NIL
logo: /images/brand/logo.png
socialInstagram: instagram.com
socialLinkedIn: linkedin.com
contactEmail: officialemail@gmail.com
contactPhone: +91 9999999999
footerText: Hi Saran Anna!
navigation: []
